/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        // Brand — primary action color. Tessera spec: #0073EA (mid-blue),
        // hover #0060B9, active a touch darker.
        brand: {
          DEFAULT: '#0073EA',
          hover:   '#0060B9',
          active:  '#004F94',
        },
        // Semantic surfaces (driven by CSS vars so dark mode swaps automatically)
        app: 'var(--bg-app)',
        surface: 'var(--bg-surface)',
        sidebar: 'var(--bg-sidebar)',
        hover: 'var(--bg-hover)',
        selected: 'var(--bg-selected)',
        dark: 'var(--bg-dark)',
        canvas: 'var(--bg-canvas)',
        card: 'var(--bg-card)',
        row: 'var(--bg-row)',
        'row-hover': 'var(--bg-row-hover)',
        'header-band': 'var(--bg-header-band)',
        elevated: 'var(--bg-elevated)',
        input: 'var(--bg-input)',
        'border-light': 'var(--border-light)',
        'border-medium': 'var(--border-medium)',
        'border-hair': 'var(--border-hair)',
        'border-default': 'var(--border-default)',
        'text-primary': 'var(--text-primary)',
        'text-secondary': 'var(--text-secondary)',
        'text-disabled': 'var(--text-disabled)',
        'text-tertiary': 'var(--text-tertiary)',
        'text-on-dark': 'var(--text-on-dark)',
        // Premium polish chip palette — OKLCH band, only hue varies.
        chip: {
          amber:  'var(--chip-amber)',
          slate:  'var(--chip-slate)',
          teal:   'var(--chip-teal)',
          pink:   'var(--chip-pink)',
          purple: 'var(--chip-purple)',
          sky:    'var(--chip-sky)',
          mint:   'var(--chip-mint)',
          coral:  'var(--chip-coral)',
        },
        // Semantic
        success: '#00C875',
        warning: '#FDAB3D',
        error: '#E2445C',
        info: '#0086C0',
        // Label palette (18 colors from design doc)
        label: {
          green: '#00C875',
          red: '#E2445C',
          orange: '#FDAB3D',
          yellow: '#FFCB00',
          purple: '#A25DDC',
          'dark-purple': '#784BD1',
          blue: '#0086C0',
          'light-blue': '#579BFC',
          teal: '#037F4C',
          'dark-teal': '#0F5662',
          pink: '#FF158A',
          'light-pink': '#FF6E92',
          lime: '#9CD326',
          grey: '#C4C4C4',
          'dark-grey': '#808080',
          brown: '#7E3B08',
          coral: '#FF7575',
          'dark-blue': '#225091',
        },
      },
      fontFamily: {
        // Tessera spec: Geist first, no Figtree. Matches --font-sans in
        // tokens.css so there's no JS/CSS mismatch.
        sans: ['Geist', 'system-ui', '-apple-system', 'BlinkMacSystemFont', '"Segoe UI"', 'sans-serif'],
        mono: ['"Geist Mono"', 'ui-monospace', '"SFMono-Regular"', 'Menlo', 'Monaco', '"Courier New"', 'monospace'],
      },
      fontSize: {
        xs: ['11px', '16px'],
        sm: ['13px', '18px'],
        base: ['14px', '20px'],
        md: ['15px', '22px'],
        lg: ['16px', '24px'],
        xl: ['20px', '28px'],
        '2xl': ['24px', '32px'],
        '3xl': ['32px', '40px'],
        hero: ['48px', '56px'],
      },
      spacing: {
        '0': '0',
        '1': '4px',
        '2': '8px',
        '3': '12px',
        '4': '16px',
        '5': '20px',
        '6': '24px',
        '8': '32px',
        '10': '40px',
        '12': '48px',
        '16': '64px',
      },
      borderRadius: {
        sm: '4px',
        DEFAULT: '6px',
        base: '6px',
        md: '8px',
        lg: '12px',
        pill: '9999px',
        // Premium polish primitives — cells are sharp, cards 12, buttons 8.
        cell: 'var(--radius-cell)',
        card: 'var(--radius-card)',
        button: 'var(--radius-button)',
      },
      boxShadow: {
        sm: '0 1px 2px rgba(0,0,0,0.04)',
        md: '0 2px 8px rgba(0,0,0,0.08)',
        lg: '0 4px 16px rgba(0,0,0,0.12)',
        xl: '0 8px 32px rgba(0,0,0,0.16)',
      },
      transitionDuration: {
        '100': '100ms',
        '150': '150ms',
        '200': '200ms',
        '250': '250ms',
      },
      transitionTimingFunction: {
        smooth: 'cubic-bezier(0.32, 0.72, 0, 1)',
      },
    },
  },
  plugins: [],
};
