/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        // Brand
        brand: {
          DEFAULT: '#0073EA',
          hover: '#0060BD',
          active: '#004B95',
        },
        // Semantic surfaces (driven by CSS vars so dark mode swaps automatically)
        app: 'var(--bg-app)',
        surface: 'var(--bg-surface)',
        hover: 'var(--bg-hover)',
        selected: 'var(--bg-selected)',
        dark: 'var(--bg-dark)',
        'border-light': 'var(--border-light)',
        'border-medium': 'var(--border-medium)',
        'text-primary': 'var(--text-primary)',
        'text-secondary': 'var(--text-secondary)',
        'text-disabled': 'var(--text-disabled)',
        'text-on-dark': 'var(--text-on-dark)',
        // Semantic
        success: '#00C875',
        warning: '#FDAB3D',
        error: '#E2445C',
        info: '#0086C0',
        // Label palette (18 colors from design doc)
        label: {
          green: '#00C875',
          red: '#E2445C',
          orange: '#FDAB3D',
          yellow: '#FFCB00',
          purple: '#A25DDC',
          'dark-purple': '#784BD1',
          blue: '#0086C0',
          'light-blue': '#579BFC',
          teal: '#037F4C',
          'dark-teal': '#0F5662',
          pink: '#FF158A',
          'light-pink': '#FF6E92',
          lime: '#9CD326',
          grey: '#C4C4C4',
          'dark-grey': '#808080',
          brown: '#7E3B08',
          coral: '#FF7575',
          'dark-blue': '#225091',
        },
      },
      fontFamily: {
        sans: ['Roboto', 'Inter', '-apple-system', 'BlinkMacSystemFont', '"Segoe UI"', 'system-ui', 'sans-serif'],
        mono: ['"Roboto Mono"', '"Fira Code"', 'monospace'],
      },
      fontSize: {
        xs: ['11px', '16px'],
        sm: ['13px', '18px'],
        base: ['14px', '20px'],
        md: ['15px', '22px'],
        lg: ['16px', '24px'],
        xl: ['20px', '28px'],
        '2xl': ['24px', '32px'],
        '3xl': ['32px', '40px'],
        hero: ['48px', '56px'],
      },
      spacing: {
        '0': '0',
        '1': '4px',
        '2': '8px',
        '3': '12px',
        '4': '16px',
        '5': '20px',
        '6': '24px',
        '8': '32px',
        '10': '40px',
        '12': '48px',
        '16': '64px',
      },
      borderRadius: {
        sm: '4px',
        DEFAULT: '6px',
        base: '6px',
        md: '8px',
        lg: '12px',
        pill: '9999px',
      },
      boxShadow: {
        sm: '0 1px 2px rgba(0,0,0,0.04)',
        md: '0 2px 8px rgba(0,0,0,0.08)',
        lg: '0 4px 16px rgba(0,0,0,0.12)',
        xl: '0 8px 32px rgba(0,0,0,0.16)',
      },
      transitionDuration: {
        '100': '100ms',
        '150': '150ms',
        '200': '200ms',
        '250': '250ms',
      },
      transitionTimingFunction: {
        smooth: 'cubic-bezier(0.32, 0.72, 0, 1)',
      },
    },
  },
  plugins: [],
};
